version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14.0
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: dnltv/foodgram_backend:v.3
    restart: always
    volumes:
      - backend_static:/app/static_backend/
      - backend_media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: dnltv/foodgram_frontend:v.3
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/var/html/static_backend/
      - backend_media:/var/html/media/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  backend_static:
  backend_media:
  data:
