# Generated by Django 4.2.1 on 2023-05-26 11:33

import core.limitations
import core.validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Required to fill in.Maximum 256 letters.', max_length=256, unique=True, verbose_name='Email address')),
                ('username', models.CharField(help_text='Required to fill in.From 3 to 32 letters.', max_length=32, unique=True, validators=[core.validators.MinLenValidator(field='username', min_len=core.limitations.Limits['MIN_LEN_USERNAME']), core.validators.OneOfTwoValidator(field='username')], verbose_name='username')),
                ('first_name', models.CharField(help_text='Required to fill in.Maximum 32 letters.', max_length=32, validators=[core.validators.OneOfTwoValidator(field='First name', first_regex='[^а-яёА-ЯЁ -]+', second_regex='[^a-zA-Z -]+')], verbose_name='First name')),
                ('last_name', models.CharField(help_text='Required to fill in.Maximum 32 letters.', max_length=32, validators=[core.validators.OneOfTwoValidator(field='Last name', first_regex='[^а-яёА-ЯЁ -]+', second_regex='[^a-zA-Z -]+')], verbose_name='Last name')),
                ('password', models.CharField(help_text='Required to fill in.Maximum 32 letters.', max_length=128, verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('username',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date of subscribe')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Author of the recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers')),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribes',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='\nRe-subscription\n'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('user')), _negated=True), name='\nIt is impossible to subscribe to yourself\n'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('username__length__gte', 3)), name='\nusername is too short\n'),
        ),
    ]
