# Generated by Django 4.2.1 on 2023-05-08 17:29

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Enter username', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='Enter e-mail', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Enter first name', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Enter last name', max_length=150, null=True)),
                ('bio', models.TextField(blank=True, help_text='Enter something about yourself', null=True, verbose_name='About me')),
                ('role', models.CharField(choices=[('admin', 'administrator'), ('moderator', 'moderator'), ('user', 'user')], default='user', max_length=20)),
                ('confirmation_code', models.CharField(blank=True, max_length=50, verbose_name='Authorization code')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('username__iexact', 'me'), _negated=True), name='username_is_not_me'),
        ),
    ]
